//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public history()
        {
            this.bills = new HashSet<bill>();
        }
    
        public int id { get; set; }
        public System.DateTime dateofsales { get; set; }
        public int total { get; set; }
    
        public virtual ICollection<bill> bills { get; set; }
    }
}
